config/routes.rb
Rails.application.routes.draw do
  get 'to_do_list/index'

  resources :lists do
    resources :items
  end

  root 'to_do_list#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
    has_many :list_items, dependent: :destroy
    validates :title, presence: true, length: { minimum: 5 }

end

app/models/list_item.rb
class ListItem < ApplicationRecord
  belongs_to :list
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

    def create
        @list = List.find(params[:list_id])
        @item = @list.list_items.create(item_params)
        
        redirect_to list_path(@list)
    end

    def destroy
        @list = List.find(params[:list_id])
        @item = @list.list_items.find(params[:id])
        @item.destroy

        redirect_to list_path(@list)
    end

    private
        def item_params
            params.require(:list_item).permit(:title, :status)
        end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

    def index
        @lists = List.all
    end

    def show
        @list = List.find(params[:id])
    end

    def new
    end

    def edit
        @list = List.find(params[:id])
    end

    def create
        @list = List.new(list_params)

        if @list.save
            redirect_to @list
        else
            render 'new'
        end

    end

    def update
        @list = List.find(params[:id])

        if @list.update(list_params)
            redirect_to @list
        else
            render 'edit'
        end
    end

    def destroy
        @list = List.find(params[:id])
        @list.destroy

        redirect_to lists_path
    end

    private
    def list_params
        params.require(:list).permit(:title, :description)
    end

end

app/controllers/to_do_list_controller.rb
class ToDoListController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/to_do_list_helper.rb
module ToDoListHelper
end

app/views/items/_form.html.erb
<%= form_with(model: [ @list, ListItem.new ], url: list_items_path(@list.id), local: true) do |form| %>
    <p>
        <%= form.label :title %><br>
        <%= form.text_field :title %>
    </p>
    <p>
        <%= form.label :status %><br>
        <%= form.text_field :status %>
    </p>
    <p>
        <%= form.submit %>
    </p>
<% end %>

app/views/items/_item.html.erb
<p>
    <strong>Item:</strong>
    <%= item.title %>
</p>
 
<p>
    <strong>Status:</strong>
    <%= item.status %>
</p>

<p>
    <%= link_to 'Destroy Item', list_item_path(item.list, item), method: :delete, data: { confirm: 'Are you sure?' } %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<%= form_with scope: :list, url: lists_path, local: true do |form| %>
 
  <% if @list && @list.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@list.errors.count, "error") %> prohibited
        this list from being saved:
      </h2>
      <ul>
        <% @list.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
    <p>
        <%= form.label :title %>
        <%= form.text_field :title %>
    </p>

    <p>
        <%= form.label :description %>
        <%= form.text_field :description %>
    </p>
 
  <p>
    <%= form.submit %>
  </p>
 
<% end %>

app/views/lists/edit.html.erb
<h1>Edit list</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', lists_path %>

app/views/lists/index.html.erb
<h1>Listing Lists</h1>
<%= link_to 'New list', new_list_path %>
<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th></th>
  </tr>
 
  <% @lists.each do |list| %>
    <tr>
      <td><%= list.title %></td>
      <td><%= list.description %></td>
      <td><%= link_to 'Show', list_path(list) %></td>
      <td><%= link_to 'Edit', edit_list_path(list) %></td>
      <td><%= link_to 'Destroy', list_path(list), method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/lists/new.html.erb
<h1>New list</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', lists_path %>

app/views/lists/show.html.erb
<p>
    <strong>Title:</strong>
    <%= @list.title %>
</p>
 
<p>
    <strong>Description:</strong>
    <%= @list.description %>
</p>

<h2>Items</h2>
<%= render partial: "items/item", collection: @list.list_items, as: @item %>

<h2>Add an item:</h2>
<%= render 'items/form' %>

<%= link_to 'Edit', edit_list_path(@list) %>
<%= link_to 'Back', lists_path %>

app/views/to_do_list/index.html.erb
<h1>Hello, Rails!</h1>
<%= link_to 'My Lists', controller: 'lists' %>